### ISSUE TITLE
Null Domain? 

### ISSUE THREAD

**Issue by weberjm** [seventag/seventag#600]
One of our customers is receiving the following error when trying to implement the container pixel on their site:

TypeError: Cannot read property '1' of null
    at getDomain (https://***************.com/containers/44.js:19:10857)
    at https://***************.com/containers/44.js:19:11725
    at Object.handle (https:/***************.com/containers/44.js:19:3167)
    at Object.handle (https:/***************.com/containers/44.js:19:8959)
    at Array.y.push (https:/***************.com/containers/44.js:19:9874)
    at https://***************.com/containers/44.js:19:8194
    
null is not an object (evaluating '/(.+)\//.exec(e)')
getDomain@https://***************.com/containers/44.js:19:10854
https://***************.com/containers/44.js:19:11734
handle@https://***************.com/containers/44.js:19:3167
handle@https://***************.com/containers/44.js:19:8965
https://***************.com/containers/44.js:19:9964

TypeError: Illegal constructor
    at TypeError (native)
    at Object.clone (https://***************.com/containers/44.js:18:19929)
    at Object.clone (https://***************.com/containers/44.js:18:19968)
    at Object.handle (https://***************.com/containers/44.js:19:9015)
    at Array.y.push (https://***************.com/containers/44.js:19:9874)
    at HTMLDocument.c (https://***************.com/containers/44.js:19:7113)

null is not an object (evaluating '/(.+)\//.exec(e)')
getDomain@https://***************.com/containers/44.js:19:10841
config/<@https://***************.com/containers/44.js:19:11725
n/this.handle@https://***************.com/containers/44.js:19:3139
n/this.handle@https://***************.com/containers/44.js:19:8957
n/h/this.bootstrap/T/y.push@https://***************.com/containers/44.js:19:9872
gautls.prototype.trkEvent@https://analytics-udg.netdna-ssl.com/gtmext/1.2.4/gtmext.min.js:15:1
gautls.prototype.trkHtml5MediaElement@https://analytics-udg.netdna-ssl.com/gtmext/1.2.4/gtmext.min.js:37:1
GasHelper.prototype._liveEvent/<@https://analytics-udg.netdna-ssl.com/gtmext/1.2.4/gtmext.min.js:7:39
GasHelper.prototype._addEventListener/fnc@https://analytics-udg.netdna-ssl.com/gtmext/1.2.4/gtmext.min.js:2:8

And also receiving a TypeError:
TypeError: Funktion erwartet at clone (https://***************.com/containers/44.js:18:19921) at clone (https://***************.com/containers/44.js:18:19958) at handle (https://***************.com/containers/44.js:19:8988) at y.push (https://***************.com/containers/44.js:19:9872) at c (https://***************.com/containers/44.js:19:7111)

From the error chain, it looks like the error is that the Domain is returning NULL, while the check is against an empty string. We think they may be serving our container pixel out of Google Tag Manager, and are trying to confirm. However, any direction you could give here would be appreciated.

**Comment by weberjm** [comment]
So, digging deeper into this, the error is coming from the following function:
` 
function getDomain(t){if(""===t)return!1;var n=/\/\/(.+)/.exec(t)[1];return/(.+)\//.exec(n)[1]}
`

Based on the fact that it only fails on the final statement, it appears that it is receiving a Referrer that is:
- not null
- begins properly with "https://" or "http://"
- does not have any trailing slash

Although this is a malformed Referrer URL, it appears that this is being sent from some domains to our customer's domain. Is there a way you would recommend to rewrite this to accept URLs without a trailing slash?

**Comment by weberjm** [comment]
Since I am not getting any replies here, I will go ahead and follow up with more of what I found and what I think needs to be changed.

The second regex used for the exec() call is 
` /(.+)\//`

While this works to strip the trailing tag on properly sent referrer URLs, using a different regex could support those cases where it is sent incorrectly, either by transmitting without the trailing slash, or by sending additional sections after the domain, i.e. 'www.google.com/abcd/ef'

Using a regex such as `/([^\/]*)/` handles these edge cases more gracefully. Please let me know if you would like me to submit a pull request on the three files I can see which use this regex:
- src/containerjs/collectors.js
- app/Resources/container-lib-sync/library.js.dist
- app/Resources/container-lib/library.js.dist

Please also let me know if there are other files which I do not have access to which have this issue.
